services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Allow all capabilities
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/workspace